export interface Product {
  id: string
  name: string
  slug: string
  price: number
  originalPrice?: number
  image: string
  category: string
  brand: string
  description: string
  features: string[]
  inStock: boolean
  rating: number
  reviews: number
}

export const products: Product[] = [
  {
    id: "1",
    name: "Predator TS 16 Curly Gen 2",
    slug: "gay-bi-a-predator-revo-12-4",
    price: 27500000,
    originalPrice: 29500000,
    image: "/g1a1.jpg",
    category: "Gậy cao cấp",
    brand: "Predator",
    description:
      "Gậy bi a Predator Revo 12.4 với công nghệ carbon fiber tiên tiến, mang lại độ chính xác và lực đánh tuyệt vời.",
    features: ["Carbon fiber shaft", "Low deflection", "Radial consistency", "Lifetime warranty"],
    inStock: true,
    rating: 5,
    reviews: 128,
  },
  {
    id: "2",
    name: "Predator Black 4-3 ",
    slug: "gay-bi-a-mit-premium",
    price: 35000000,
    image: "/g2a1.jpg",
    category: "Gậy trung cấp",
    brand: "Predator",
    description:  
      "Predator Black 4-3 được chế tác thủ công với gỗ maple chất lượng cao, phù hợp cho người chơi chuyên nghiệp.",
    features: ["Maple wood", "Handcrafted", "Balance technology", "Bảo hành 2 năm"],
    inStock: true,
    rating: 4.8,
    reviews: 95,
  },
  {
    id: "3",
    name: "Gậy Bi A Panthera 9-2",
    slug: "gay-bi-a-fury-fc-01",
    price: 120000000,
    originalPrice: 130000000,
    image: "/g3a1.jpg",
    category: "Gậy cao cấp",
    brand: "Panthera",
    description: "Gậy bi a Panthera 9-2 với thiết kế sang trọng và công nghệ giảm độ lệch hiện đại.",
    features: ["Low deflection shaft", "Solid core", "Stainless steel joint", "Tiger tip"],
    inStock: true,
    rating: 4.6,
    reviews: 72,
  },
  {
    id: "4",
    name: "Gậy phá BK Rush ",
    slug: "gay-bi-a-dragon-classic",
    price: 38000000,
    image: "/g4a1.jpg",
    category: "Gậy phổ thông",
    brand: "BK Rush",
    description: "Gậy phá BK Rush phù hợp cho người mới bắt đầu với giá cả phải chăng và chất lượng tốt.",
    features: ["Carbon fiber shaft", "Low deflection", "Radial consistency", "Lifetime warranty"],
    inStock: true,
    rating: 4.3,
    reviews: 156,
  },
  {
    id: "5",
    name: "Predator ikon 4-5",
    slug: "gay-bi-a-predator-p3-revo",
    price: 35000000,
    image: "/g5a1.jpg",
    category: "Gậy cao cấp",
    brand: "Predator",
    description: "Predator ikon 4-5 được chế tác thủ công với gỗ maple chất lượng cao, phù hợp cho người chơi chuyên nghiệp.",
    features: ["Maple wood", "Handcrafted", "Balance technology", "Bảo hành 2 năm"],
    inStock: true,
    rating: 4.9,
    reviews: 89,
  },
  {
    id: "6",
    name: "Cuetec SVB",
    slug: "gay-bi-a-fury-ap-2",
    price: 11000000,
    image: "/g6a1.jpg",
    category: "Gậy cao cấp",
    brand: "Cuetec",
    description: "Gậy bi a Cuetec SVB dòng cao cấp với công nghệ composite hiện đại.",
    features: ["Composite shaft", "Pro taper", "Uniloc joint", "Bảo hành 3 năm"],
    inStock: false,
    rating: 4.7,
    reviews: 67,
  },
  {
    id: "7",
    name: "Nhảy Cuetec Propel V4",
    slug: "gay-bi-a-fury-ap-2",
    price: 12000000,
    image: "/g7a1.jpg",
    category: "Gậy cao cấp",
    brand: "Cuetec",
    description: "Nhảy Cuetec Propel V4 chất lượng cao, phá bóng tốt.",
    features: ["Carbon fiber shaft", "Low deflection", "Radial consistency", "Lifetime warranty"],
    inStock: true,
    rating: 4.9,
    reviews: 168,
  },
  {
    id: "8",
    name: "Cuetec Apolo",
    slug: "gay-bi-a-fury-ap-2",
    price: 25000000,
    image: "/g8a1.jpg",
    category: "Gậy trung cấp",
    brand: "Cuetec",
    description: "Cuetec Apolo được chế tác thủ công với gỗ maple chất lượng cao, phù hợp cho người chơi chuyên nghiệp.",
    features: ["Maple wood", "Handcrafted", "Balance technology", "Bảo hành 2 năm"],
    inStock: true,
    rating: 4.9,
    reviews: 128,
  },
  {
    id: "9",
    name: "Cuetec Gen2",
    slug: "gay-bi-a-cuetec-gen2",
    price: 15000000,
    image: "/g9a1.jpg",
    category: "Gậy phổ thông",
    brand: "Cuetec",
    description: "Cuetec Gen2 được chế tác thủ công với gỗ maple chất lượng cao, phù hợp cho người chơi chuyên nghiệp.",
    features: ["Carbon fiber shaft", "Low deflection", "Radial consistency", "Lifetime warranty"],
    inStock: true,
    rating: 4.9,
    reviews: 122,
  },
  {
    id: "10",
    name: "Mezz ACE",
    slug: "gay-bi-a-mezz-ace",
    price: 75000000,
    image: "/g10a1.jpg",
    category: "Gậy cao cấp",
    brand: "Mezz",
    description: "Mezz ACE là dòng gậy cao cấp của Mezz, phù hợp cho người chơi chuyên nghiệp.",
    features: ["Carbon fiber shaft", "Low deflection", "Radial consistency", "Lifetime warranty"],
    inStock: true,
    rating: 4.7,
    reviews: 128,
  },
  {
    id: "11",
    name: "Mezz ACE 2181",
    slug: "gay-bi-a-mezz-ace-2181",
    price: 75000000,
    image: "/g11a1.jpg",
    category: "Gậy trung cấp",
    brand: "Mezz",
    description: "Mezz ACE 2181 là dòng gậy trung cấp của Mezz, phù hợp cho người chơi chuyên nghiệp.",
    features: ["Maple wood", "Handcrafted", "Balance technology", "Bảo hành 2 năm"],
    inStock: true,
    rating: 4.7,
    reviews: 128,
  },
  {
    id: "12",
    name: "Phá Mezz Kai",
    slug: "gay-bi-a-phap-mezz-kai",
    price: 13000000,  
    image: "/g12a1.jpg",
    category: "Gậy phổ thông",
    brand: "Mezz",
    description: "Phá Mezz Kai là dòng gậy phổ thông của Mezz, giúp phá bóng tốt và chất lượng tốt với thiết kế đẹp.",
    features: ["Maple wood", "Handcrafted", "Balance technology", "Bảo hành 2 năm"],
    inStock: true,
    rating: 4.5,
    reviews: 475,
  },
  {
    id: "13",
    name: "Mezz EC9",
    slug: "gay-bi-a-mezz-ec9",
    price: 12000000,  
    image: "/g13a1.jpg",
    category: "Gậy phổ thông",
    brand: "Mezz",
    description: "Mezz EC9 là dòng gậy phổ thông của Mezz, với thiết kế đẹp và chất lượng tốt.",
    features: ["Maple wood", "Handcrafted", "Balance technology", "Bảo hành 2 năm"],
    inStock: true,
    rating: 4.5,
    reviews: 231,
  },
  {
    id: "14",
    name: "Mezz Axi 158",
    slug: "gay-bi-a-mezz-axi-158",
    price: 18000000,  
    image: "/g14a1.jpg",
    category: "Gậy trung cấp",
    brand: "Mezz",
    description: "Mezz Axi 158 là dòng gậy trung cấp của Mezz, với thiết kế đẹp và chất lượng tốt, đem lại cảm giác chơi thoải mái và dễ dàng.",
    features: ["Carbon fiber shaft", "Low deflection", "Radial consistency", "Lifetime warranty"],
    inStock: true,
    rating: 4.7,
    reviews: 341,
  },
  {
    id: "15",
    name: "Peri VK 01",
    slug: "gay-bi-a-mezz-axi-158",
    price: 13000000,  
    image: "/g15a1.jpg",
    category: "Gậy trung cấp",
    brand: "Peri",
    description: "Peri VK 01 là dòng gậy trung cấp của Peri, với thiết kế đẹp và chất lượng tốt, đem lại cảm giác chơi thoải mái và dễ dàng, phù hợp cho người chơi chuyên nghiệp.",
    features: ["Carbon fiber shaft", "Low deflection", "Radial consistency", "Lifetime warranty"],
    inStock: true,
    rating: 4.9,
    reviews: 244,
  },
  {
    id: "16",
    name: "Peri PTE 04",
    slug: "gay-bi-a-peri-pte-04",
    price: 13000000,  
    image: "/g16a1.jpg",
    category: "Gậy phổ thông",
    brand: "Peri",
    description: "Peri PTE 04 dòng gậy phổ thông của Peri, với thiết kế đẹp và chất lượng tốt, được nhiều người chơi chọn.",
    features: ["Maple wood", "Handcrafted", "Balance technology", "Bảo hành 1 năm"],
    inStock: true,
    rating: 4.5,
    reviews: 328,
  },
  {
    id: "17",
    name: "Peri CV 01",
    slug: "gay-bi-a-peri-cv-01",
    price: 13000000,  
    image: "/g17a1.jpg",
    category: "Gậy phổ thông",
    brand: "Peri",
    description: "Peri CV 01 dòng gậy phổ thông của Peri, với thiết kế đẹp và chất lượng tốt, được nhiều người chơi chọn.",
    features: ["Carbon fiber shaft", "Low deflection", "Radial consistency", "Lifetime warranty"],
    inStock: true,
    rating: 4.5,
    reviews: 228,
  },
  {
    id: "18",
    name: "Peri PD 10",
    slug: "gay-bi-a-peri-pd-10",
    price: 5000000,  
    image: "/g18a1.jpg",
    category: "Gậy phổ thông",
    brand: "Peri",
    description: "Peri PD 10 dòng gậy phổ thông của Peri, với thiết kế đẹp và chất lượng tốt, phù hợp cho người mới bắt đầu.",
    features: ["Maple wood", "Handcrafted", "Balance technology", "Bảo hành 1 năm"],
    inStock: true,
    rating: 4.7,
    reviews: 110,
  },
  {
    id: "19",
    name: "Peri PD 05",
    slug: "gay-bi-a-peri-pd-05",
    price: 4500000,  
    image: "/g19a1.jpg",
    category: "Gậy phổ thông",
    brand: "Peri",
    description: "Peri PD 10 dòng gậy phổ thông của Peri, với thiết kế đẹp và chất lượng tốt, phù hợp cho người mới bắt đầu.",
    features: ["Carbon fiber shaft", "Low deflection", "Radial consistency", "Lifetime warranty"],
    inStock: true,
    rating: 4.8,
    reviews: 105,
  },
]

export const categories = [
  { name: "Tất cả", slug: "all" },
  { name: "Gậy cao cấp", slug: "gay-cao-cap" },
  { name: "Gậy trung cấp", slug: "gay-trung-cap" },
  { name: "Gậy phổ thông", slug: "gay-pho-thong" },
]

export const brands = ["Mit", "Predator", "Fury", "Dragon", "Mezz", "Cuetec"]
